stages:
  split_subsets:
    cmd: python src/data/dataset_splitter.py --dataset-path data/external/defects/train --output-dataset-path data/processed/defects/
    deps:
      - src/data/dataset_splitter.py
      - data/external/defects/train
    outs:
      - data/processed/defects
  train_model:
    cmd: python src/train.py --dataset-path data/processed/defects --device cuda --batch-size 256 --img-size 32 --num-epochs 25
    deps:
      - src/train.py
      - data/processed/defects
    outs:
      - defects
      - models